<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <HhDllCompilateDir>\\servertest\Bus\Buoninfante\Asc\SINTESI\Setup\DllPersonalizzateCompilate\</HhDllCompilateDir>
  </PropertyGroup>

  <Target Name="HhCopiaDllCompilate"
          AfterTargets="Build"
          Condition="'$(OutputType)' == 'Library'">
    <MakeDir Directories="$(HhDllCompilateDir)" />
    <Copy SourceFiles="$(TargetPath)"
          DestinationFolder="$(HhDllCompilateDir)"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(TargetDir)$(TargetName).pdb"
          DestinationFolder="$(HhDllCompilateDir)"
          SkipUnchangedFiles="true"
          Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
  </Target>
</Project>
